INSERT INTO users (ID, USERNAME, PASSWORD, ROLE) VALUES (1, 'drew_erskine', 'erskine321', 'ROLE_USER');
INSERT INTO users (ID, USERNAME, PASSWORD, ROLE) VALUES (2, 'sarah1', 'huang321', 'ROLE_ADMIN');

INSERT INTO cash_card (ID, AMOUNT, OWNER) VALUES (99, 123.45, 'sarah1');
INSERT INTO cash_card (ID, AMOUNT, OWNER) VALUES (100, 1.00, 'sarah1');
INSERT INTO cash_card (ID, AMOUNT, OWNER) VALUES (101, 150.00, 'sarah1');
INSERT INTO cash_card (ID, AMOUNT, OWNER) VALUES (102, 200.00, 'kumar2');
